### ISSUE TITLE
Site not detecting Figma

### ISSUE THREAD

**Issue by Carnageous** [fingerprintjs/external-protocol-flooding#13]
I used the app and have Figma v 97.7 installed, but the site did not detect it.
I opened figma and did a re-login and tested again with the app open, but still without success.

Tested on Windows 10

**Comment by spalt08** [comment]
Can you please check if your browser can open `figma://` links? 
You may invoke `document.location.replace` or just create an HTML link and click on it.

**Comment by Carnageous** [comment]
Yes, this works. For example, I created figma://test and this opnened figma. I can also verify this by using figmas "login via browser" option: This also creates a figma link and opens it.

**Comment by spalt08** [comment]
Got it, thanks. What browsers did you try?

**Comment by Carnageous** [comment]
When I reported this, only Chrome 92 (Chrome Dev version if that makes a difference)
Tried it right now with Firefox and MS Edge and it worked in both cases.

I also just noticed the same thing for Postman -> Works in Firefox and Edge, not in chrome.

**Comment by spalt08** [comment]
The accuracy can be low because of:
* Custom browser settings or flags - The demo was designed for the default setup, but that doesn’t mean your custom setup is not vulnerable.
* Poorly performant hardware (including virtual machines) - Some timings are just hardcoded and were tested on the MacBook hardware.
* Fullscreen mode - The demo will work faster and more accurate if the browser is not in a fullscreen mode
* Slow internet connection
* Gestures during the process

I also made a special branch for Chromium (Chrome, Brave, Edge, etc.) that works much slower, but should be more accurate.
https://609d9f4d79c4f6000700782c--boring-visvesvaraya-dbefd4.netlify.app/

It still may not work for your browser with a custom configuration. Like downloading PDFs instead of opening it.

**Comment by Carnageous** [comment]
Thank you for the explaination! That branch detected both Postman and Figma successfully for me.

**Comment by spalt08** [comment]
may be related with #17
